### ISSUE TITLE
Pre-survey

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-Kansas#12]
Could combine registration w/ pre-survey as we did here:
https://docs.google.com/forms/d/1yWyPP-UaHTa8k8TBtsCIXWFxg0QBxv6g0g1p5y0aRSE/edit

Tweak to make more event specific, include lunch discussion topic ideas.

**Comment by jbkieffer** [comment]
Registration form is live at Eventbrite: [https://www.eventbrite.com/e/mozilla-working-open-workshop-tickets-37918290628?aff=eac2](https://www.eventbrite.com/e/mozilla-working-open-workshop-tickets-37918290628?aff=eac2)
Will hang on to the survey, though, as we'll need something like this to prep attendees.

**Comment by jbkieffer** [comment]
Assigning Kelly and other KU team members to this issue to get the pre-workshop survey out to registrants by Wednesday, 10/11.

**Comment by kspavin** [comment]
Pre survey sent to all attendees as of 2:00 (CST) on Friday, October 6. Link to responses here: https://docs.google.com/spreadsheets/d/1A-nsFCBhlnynNCWTj0Ms33ePx_ElT76qG1-E3TR9emI/edit?usp=sharing

**Comment by stephwright** [comment]
Looks like we have 7 responses (incl Josh).  Shall we send this out again with the reminder email one week prior... esp if we have new peeps.

**Comment by kspavin** [comment]
Sure thing! Will re-send this afternoon.

**Comment by stephwright** [comment]
WOW... you're quick!  Thanks @kspavin !!! 🥇
