### ISSUE TITLE
POP needed for event

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-Kansas#13]
We use a POP model for our events (even our internal mtgs) to:
    Help others and yourself get clear on the purpose and outcomes of any intended action
    Help instill in individuals, teams, and organizations an ongoing discipline of focusing on RESULTS rather than activity
    Create more REAL results with less effort

We like to start our WOWs w/ a POP so participants know the why, what, and how of the event. How it works:  
**PURPOSE** - Why? Why are we undertaking this? What is the purpose?  
        ie. to get decision on sponsoring an event
**OUTCOMES** - What are the specific outcomes we want to accomplish as a result of this action?
        ie. final decision and to make clear and plan next steps
**PROCESS** - What steps will we take to achieve these outcomes and fulfill the purpose?
        Ie. 30 minutes ~ 10 minute share options, 10 minutes discussions, 10 minutes to make choice and assign next steps

_ex. POP for South Africa WOW_

**Purpose**
Support and grow the open research movement in South Africa and beyond
**Outcomes**
Participants feel comfortable going out and advocating for / leading conversations & activities around open research
**Process**
Connect people in the open community
Expose participants to best practices around open, plus delivery mode
Provide a space for brainstorming and organizing open convos and activities in your communities

**Comment by stephwright** [comment]
@jbkieffer do you and your team feel comfortable identifying the POP for this workshop?

**Comment by jbkieffer** [comment]
Will get the Kansas team on this and get back to you.

**Comment by KUJoshB** [comment]
Hey @stephwright: how does this look as a draft?

PURPOSE - Support integration of open practices into projects, where appropriate, to include inception, design, method, data, publications, and other research and teaching outputs.
OUTCOMES - Participants feel comfortable employing open tools and practices in projects and can articulate the value of open to colleagues.
PROCESS - Define open practices and open actions in an academic environment. 
Explore open tools and workflows for academic and curricular projects.
Apply open approaches to participant projects and communities.

**Comment by stephwright** [comment]
Beautiful!  Only recommendation is to strike the second half of Purpose as below.  More detailed then you need to get in the Purpose... simpler is better. :)

PURPOSE - Support integration of open practices into projects, where appropriate ~~, to include inception, design, method, data, publications, and other research and teaching outputs.~~
OUTCOMES - Participants feel comfortable employing open tools and practices in projects and can articulate the value of open to colleagues.
PROCESS - Define open practices and open actions in an academic environment.
Explore open tools and workflows for academic and curricular projects.
Apply open approaches to participant projects and communities.
