### ISSUE TITLE
Supplies

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-Kansas#15]
- [x]  power strips for tables
- [x] post-it flip charts x2
- [x] flip chart pens
- [x] nametags
- [x] medium sized sticky notes of 2 different colors (usu red & green)
- [x] pens & paper
- [x] swag (stickers)
- [x] printed pre/post-event survey
- [x] printouts for activities
  - [x] Open Canvas
  - [x] Open Leadership Bingo

**Comment by kspavin** [comment]
There's a good chance I may have missed this elsewhere, but where can I find the activity documents? I'll run some copies of those tomorrow if a kind soul can point me in the right direction!

**Comment by stephwright** [comment]
You didn't miss anything @kspavin ... just added that info today as we were finalizing the slide deck :)  
* Open Leadership Bingo (one per participant): https://drive.google.com/open?id=1QaUPeIHvU5YzWG86T_qbbxA5igLHGx-indwDGOo71kM
* Open Canvas (one per participant / double-sided): https://goo.gl/to6PYn
* Challenges to Open Data (one per participant / double-sided): https://docs.google.com/document/d/1Uwow7fOz7hsYPxjOqc_bhCEGW30mUFUeTSDhfxBvG-Q/edit?usp=sharing
* DATA_README checklist (one per table +2 extra / double-sided): https://docs.google.com/document/d/1oTiyttQbH74z7swgu8X_1DwTUKVbi-B1GDuNQe3MKLE/edit?usp=sharing
