### ISSUE TITLE
post-event survey?

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-Kansas#16]
Might I recommend a paper post-event survey?
In the past I've tied sticker distribution / certificate distribution / something at the end distribution to handing in the paper post-event survey.  Gets folks to actually do it (as they are frequently a) out of battery, or already closed up their laptops).

Thoughts?

**Comment by kspavin** [comment]
Sounds like a good plan to me! I've requested lots of power options in the room to hopefully skirt that out-of-battery issue, but paper will work too! Are those surveys something you'd be bringing along, or will we need to create and make copies? Happy to help either way!

**Comment by stephwright** [comment]
Here's a pre/post assessment survey we used for a GitHub workshop we ran: https://docs.google.com/document/d/1_N5ZSVvcNUp6F5xLPGw9JzeeZAhmMCtwFY6z6gL7vXY/edit#heading=h.famzc66fhruq

If interested, I can tweak to use questions of interest for this event. Here's an example of what it might look like: https://docs.google.com/document/d/17IsetuHSbmEg0XmLED1Y22fOu94c1ouxRgEkE-oW1KU/edit?usp=sharing
