### ISSUE TITLE
Update schedule on website

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-Kansas#3]
Draft schedule here: https://docs.google.com/document/d/197xKxdOZsmmfMFVmENfBY7aUH1XtfkiEvPuMND9CoAs/edit

- [x] Josh will run by organizing team.  
- [x] Steph will run by Zannah and Abby.
- [x] Upon agreement, needs to be updated on website

**Comment by stephwright** [comment]
How are we on the schedule? Do we have it settled on the KU side?

**Comment by jbkieffer** [comment]
It seems to be pretty settled on KU's side - the team was going on the schedule you and Josh created over the phone. I've edited both Day 1 and Day 2 on the website according to that [schedule](https://docs.google.com/document/d/1kF8-ibnHeSofpZ7p0mEICWjKJ3IRauyoHHoMNWTEva8).
