### ISSUE TITLE
Update workshop materials for Kansas location

### ISSUE THREAD

**Issue by jbkieffer** [mozillascience/WOW-Kansas#5]
* Google Doc Presentations currently say "Boston" on title slide
* Need update to say "Kansas" along with appropriate presenter name

**Comment by stephwright** [comment]
I will update this weekend.

**Comment by jbkieffer** [comment]
Are there presentations you want linked from the schedule? Happy to do this if they're updated and ready.

**Comment by stephwright** [comment]
Working on them here.  Currently putting them all in one long slidedeck for ease of use during the day and editing.  If you want to break them out into separate presentations to link separately on the website, that'd be awesome!  

https://docs.google.com/presentation/d/1fICkE6EIMG8J-mR3mhdP982EVnaawOVbJzoPQ3nN7kk/edit?usp=sharing

**Comment by stephwright** [comment]
Actually... on second thought.  Probably best to wait until we're done tweaking.  I'll add the separate slide decks to the website Sunday night

**Comment by jbkieffer** [comment]
Sounds good!

**Comment by stephwright** [comment]
Here's the Faciltator's Annotated Schedule: https://docs.google.com/document/d/14JJFfgfTMQAl2ocWgt6h4hu59my_JUXDnQIOJJGHsU4/edit?usp=sharing

**Comment by stephwright** [comment]
Individual presentations linked on the website.
