### ISSUE TITLE
Safety Team needs members

### ISSUE THREAD

**Issue by jbkieffer** [mozillascience/WOW-Kansas#7]
* Safety Team is currently "more to come" on the event website
* When team members are appointed, update the website

**Comment by stephwright** [comment]
Do you have folks that are comfortable acting as safety team members.  Usually we have one Moz and one local host.  What is your preference?

**Comment by jbkieffer** [comment]
One Moz and one local person makes sense. I will check with the team and see who wants to do this.

**Comment by stephwright** [comment]
I've got a ? out to our team too.  Will add when decided on who

**Comment by stephwright** [comment]
Jenn Beard has agreed to this on our team.  Is there someone from KU willing to take on the Safety Cmte role?

**Comment by jbkieffer** [comment]
I'm taking that role from the local team. Was just waiting on the Moz team member to update that part of the website.

**Comment by jbkieffer** [comment]
Updating that now; if you can add Jenn's email address that would help - or comment on the issue with it and I'll add it to the page.

**Comment by stephwright** [comment]
Will do!  I'll add it here in case it's needed for other things as well: jenn@mozillafoundation.org

**Comment by stephwright** [comment]
Added both to the etherpad for the event.
